"""revised relationships

Revision ID: 21a95abf653d
Revises: 9ea6e3ccb441
Create Date: 2025-02-07 20:42:35.624231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine
from alembic.operations import Operations
from sqlalchemy.ext.declarative import declarative_base


# revision identifiers, used by Alembic.
revision = '21a95abf653d'
down_revision = '9ea6e3ccb441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('restaurant_pizzas') as batch_op:
        # Add the columns first
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pizza_id', sa.Integer(), nullable=True))

    # Create the foreign key for 'restaurant_id' separately
     with op.batch_alter_table('restaurant_pizzas') as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_restaurant_pizzas_restaurant_id_restaurants'),
            'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE'
        )

    # Create the foreign key for 'pizza_id' separately
     with op.batch_alter_table('restaurant_pizzas') as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_restaurant_pizzas_pizza_id_pizzas'),
            'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE'
        ) 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas') as batch_op:
        # Drop the foreign keys
        batch_op.drop_constraint(op.f('fk_restaurant_pizzas_pizza_id_pizzas'), type_='foreignkey')
        batch_op.drop_constraint(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), type_='foreignkey')
        # Drop the columns
        batch_op.drop_column('pizza_id')
        batch_op.drop_column('restaurant_id')
    # ### end Alembic commands ###
